### PR TITLE
Always test the latest versions of Angular

### LINKED ISSUE #5: Test Angular 1.2.0 - 1.2.10 in Jasmine 1
`npm install karma-jasmine@0.1.6` for Karma to use Jasmine 1, then change test code to support both Jasmine 1 and 2 and make sure tests pass.

### PR DESCRIPTION
**Pull request by henrahmagix**
Angular 1.4.10 was released before this package released 1.0.0. Instead of
having to keep up-to-date on new Angular versions, we can instead install
whatever the latest is in the test suite. That way we can check support by just
re-running a suite on master.

@incuna/frontend Please merge, ta!

Fix #5

### CODE REVIEW

**Comment by henrahmagix** [comment]
@incuna/frontend I've made a mistake: the angular versions aren't being tested, always the latest 1.4 is being installed. Working on it

**Comment by wytrych** [comment]
A mistake!

**Comment by henrahmagix** [comment]
There's an issue with angular-mocks 1.2.0 to 1.2.10: they don't work with Jasmine 2. See https://github.com/angular/angular.js/blob/master/CHANGELOG.md#1211-cryptocurrency-hyperdeflation-2014-02-03

**Comment by henrahmagix** [comment]
It's going to be too much at the moment to support Jasmine 1.3 in the tests, so instead the tests will be limited to Angular 1.2.11+

**Comment by henrahmagix** [comment]
@incuna/frontend Ready!

**Comment by henrahmagix** [comment]
@incuna/frontend  Bump

**Comment by wytrych** [comment]
Tests don't seem to run https://travis-ci.org/incuna/angular-touch-no-ng-click/jobs/116613202#L609

**Comment by wytrych** [comment]
Also, could you turn off DEBUG in Karma? The output is hard to read

**Comment by henrahmagix** [comment]
> Tests don't seem to run

@wytrych They do, it's just how the terminal line is being updated, it's not buffering the line (or something), instead it's outputting every update on every line but missing the number of tests that have run. If 0 tests run, that's a failure, hence why most projects start with 1 test of `expect(true).toBe(true)`

**Comment by wytrych** [comment]
Cold you remove `DEBUG` though, so it's easier to see what's going on?

**Comment by henrahmagix** [comment]
@wytrych Done in 426109f

**Comment by wytrych** [comment]
Thanks

**Comment by wytrych** [comment]
Still seems to be running in DEBUG :(

**Comment by henrahmagix** [comment]
Ah, `DEBUG=true` is set in `.travis.yml` for verbose logs from `scripts/setBowerResolution.js`. I'd like to keep it that way.

I think it's good to have debug logs in Travis so if a problem occurs you can really see what's going on. Verbosity in Travis builds means you don't have to guess: all the information you could get is logged.

**Comment by wytrych** [comment]
This debug information isn't really helpful and it's difficult to see the actual tests. I also think that `Executed 0 of 7 SUCCESS (0 secs / 0 secs)` might go away if you turn off Debug

**Comment by henrahmagix** [comment]
But you can see multiple `SUCCESS` logs, one for each test, 7 in total. I'll look into it

**Comment by henrahmagix** [comment]
@wytrych Updated, but the multiple `SUCCESS` logs are still the same. Not sure why but I don't think it's necessary to try to fix right now.

**Comment by henrahmagix** [comment]
Actually, think I've fixed it by replacing the `progress` reporter with the `dots` reporter.

**Comment by henrahmagix** [comment]
Fix #5

**Comment by henrahmagix** [comment]
@incuna/js Testing is finalised now. Please merge, ta!

**Comment by henrahmagix** [comment]
Thanks!

**Pull request merged**
